// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBIQwgUZlxDSHV8-v78VJ6UOASBx0l6OU',
    appId: '1:495669461131:web:4468207a00c965a2a7548e',
    messagingSenderId: '495669461131',
    projectId: 'facilityfix-6d27a',
    authDomain: 'facilityfix-6d27a.firebaseapp.com',
    storageBucket: 'facilityfix-6d27a.firebasestorage.app',
    measurementId: 'G-CTYHR31S0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe1P1076wLTs6C6RHAAo-pEernmDxUdWM',
    appId: '1:495669461131:android:7bf2c59115c9e6e6a7548e',
    messagingSenderId: '495669461131',
    projectId: 'facilityfix-6d27a',
    storageBucket: 'facilityfix-6d27a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALZ01rp16qmzg5SJa-_dQ-Wbb6bCe0GIw',
    appId: '1:495669461131:ios:762f0e47c024c4a3a7548e',
    messagingSenderId: '495669461131',
    projectId: 'facilityfix-6d27a',
    storageBucket: 'facilityfix-6d27a.firebasestorage.app',
    iosClientId: '495669461131-trcd301duc0ooael3ojjr0beb2sk07ao.apps.googleusercontent.com',
    iosBundleId: 'com.example.facilityfix',
  );

}